version: "3"

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $container_id
# docker-compose images
# docker-compose logs --tail 20 repo_name

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - app-tier
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: always
  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
